services:
  chat2api:
    image: ghcr.io/narrator-z/chat2api-docker:latest

    container_name: chat2api

    ports:
      - "14500:14500"
      - "58002:8080"
    environment:
      - DISPLAY=:99

    volumes:
      - ./downloads:/app/downloads
      - ./start.sh:/app/start.sh:ro
      - ./config:/root

    restart: always

networks:
  chat2api:
    external: true
    name: chat2api
