services:
  electron:
    build: .
    container_name: chat2api
    environment:
      - USE_GITHUB_CDN=true
    ports:
      - "6080:6080"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config:/root/
      - ./downloads:/app/downloads
networks:
  chat2api:
    external: true
    name: chat2api